### PR TITLE
hm - added delete button

### LINKED ISSUE #57: Add Delete Column to ReviewTable (if not already done)
- [x] Added Delete column button to ReviewTable
- [x] Gets 100% Code coverage
- [x] Works on localhost as expected
- [x] Works on heroku-qa as expected.

### PR DESCRIPTION
**Pull request by huntermassey33**
# Overview

Added delete button to review table, 100% test coverage

# Issues Addressed

Addresses #31

### CODE REVIEW

**Review by JohnK-mi — APPROVED** [review]
code looks good, and everything works properly when run locally

**Review by JohnK-mi — CHANGES_REQUESTED** [review]
MenuItemTableIndexPage.test.js has an issue where the parameter "id" is not given when deleting on line 146

**Review by JohnK-mi — APPROVED** [review]
requested change was made

**Review by kevin2hang — APPROVED** [review]
Looks good to me!

**Pull request merged**
